/**
  ******************************************************************************
  * File Name          : boost_converter.c
  * Description        : This file provides code to control the boost converter
  ******************************************************************************
  */

 /* Includes ------------------------------------------------------------------*/
#include "boost_converter.h"

/* Variables ------------------------------------------------------------------*/
volatile uint16_t Duty_Cycle_Current = DUTY_CYCLE_10_PERCENT;
volatile uint16_t Duty_Cycle_Previous = DUTY_CYCLE_30_PERCENT;
volatile float P_IN_Previous = 0;
extern float VDDA;
extern Turbine_StatusTypeDef Turbine_Status;

/**
  * @brief  This function attempts to maximize the power generated by the Wind Turbine
  * 		by using maximum power point tracking (MPPT)/ Perturb and Observe algorithm
  * 		to change the boost converter's Duty Cycle.
  * 		Desired operating Voltage = 12V , Vmin = 10V, Vmax = 14V.
  * @param  Voltage and Current at the load
  * @retval none
  */
void Perturb_Observe(float V_LOAD, float I_LOAD)
{
	float P_IN_Current = V_LOAD*I_LOAD - I_LOAD*I_LOAD*(SHUNT_RESISTOR);
	
	/* P controller */
	if(V_LOAD > V_MAX)
		{
			Duty_Cycle_Previous = Duty_Cycle_Current;
			Duty_Cycle_Current = Duty_Cycle_Previous + (V_LOAD - V_MAX)*BOOST_KP;
		}
	else if(V_LOAD < V_MIN)
		{
			Duty_Cycle_Previous = Duty_Cycle_Current;
			if(Duty_Cycle_Previous - (V_MIN - V_LOAD)*BOOST_KP > 0)							//Prevents underflow
			Duty_Cycle_Current = Duty_Cycle_Previous - (V_MIN - V_LOAD)*BOOST_KP;
			else Duty_Cycle_Current = 0;
		}

	/* Perturb and observe algorithm */
	else if(P_IN_Current - P_IN_Previous > 0.0f)
		{
			if(Duty_Cycle_Current - Duty_Cycle_Previous >= 0)
				{
					Duty_Cycle_Previous = Duty_Cycle_Current;
					Duty_Cycle_Current = Duty_Cycle_Current + DELTA_DUTY_CYCLE;
				}
			else if(Duty_Cycle_Current - Duty_Cycle_Previous < 0)
				{
					Duty_Cycle_Previous = Duty_Cycle_Current;
					if(Duty_Cycle_Current - DELTA_DUTY_CYCLE > 0)					//Prevents underflow
					Duty_Cycle_Current = Duty_Cycle_Current - DELTA_DUTY_CYCLE;
					else Duty_Cycle_Current = 0;
				}
		}
	else if(P_IN_Current - P_IN_Previous < 0.0f)
		{
			if(Duty_Cycle_Current - Duty_Cycle_Previous >= 0)
				{
					Duty_Cycle_Previous = Duty_Cycle_Current;
					if(Duty_Cycle_Current - DELTA_DUTY_CYCLE > 0)					//Prevents underflow
					Duty_Cycle_Current = Duty_Cycle_Current - DELTA_DUTY_CYCLE;
					else Duty_Cycle_Current = 0;
				}
			else if(Duty_Cycle_Current - Duty_Cycle_Previous < 0)
				{
					Duty_Cycle_Previous = Duty_Cycle_Current;
					Duty_Cycle_Current = Duty_Cycle_Current + DELTA_DUTY_CYCLE;
				}
		}
		/* Set to max duty cycle if its greater than the max value */
		if(Duty_Cycle_Current>MAX_PWM_COUNT) Duty_Cycle_Current = MAX_PWM_COUNT;

		__HAL_TIM_SET_COMPARE(&htim11,TIM_CHANNEL_1,Duty_Cycle_Current);
		P_IN_Previous = P_IN_Current;

		/* --------------Safety Contingencies-------------- */
		/* Stops the rotor if the electric brake is applied */
		if(Turbine_Status == STOP)
			{
				Duty_Cycle_Previous = MAX_PWM_COUNT;
				__HAL_TIM_SET_COMPARE(&htim11,TIM_CHANNEL_1,Duty_Cycle_Previous);
			}
		/* Stops the rotor from producing power incase s.c. occurs on the output */
		if(ABS(V_LOAD - I_LOAD*SHUNT_RESISTOR) < SC_VOLT_DIFF) Duty_Cycle_Previous = MAX_PWM_COUNT;

}

